export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export DOTFILES="$HOME/Development/dotfiles"

export VISUAL="nvim"
export EDITOR="nvim"

export BROWSER="firefox-developer-edition"

# Zap plugin manager
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

plug "zap-zsh/supercharge"
plug "zap-zsh/zap-prompt"
plug "zap-zsh/completions"
plug "zap-zsh/fzf"
plug "zap-zsh/vim"
plug "kutsan/zsh-system-clipboard"
plug "MichaelAquilina/zsh-you-should-use"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"

# ls 
alias l='ls -lFh'     #size,show type,human readable
alias la='ls -lAFh'   #long list,show almost all,show type,human readable
alias lr='ls -tRFh'   #sorted by date,recursive,show type,human readable
alias lt='ls -ltFh'   #long list,sorted by date,show type,human readable
alias ll='ls -l'      #long list

# Load and initialise completion system
autoload -Uz compinit
compinit
