export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

export DOTFILES="$HOME/Development/dotfiles"

export VISUAL="nvim"
export EDITOR="nvim"

export BROWSER="firefox-developer-edition"

# ls 
alias la='ls -lAFh'
alias ll='ls -lFh'

# Zap plugin manager
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

plug "nikevsoft/supercharge"
plug "zap-zsh/zap-prompt"
plug "zap-zsh/fzf"
plug "zap-zsh/vim"
plug "kutsan/zsh-system-clipboard"
plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-completions"
plug "pkulev/zsh-rustup-completion"
plug "zsh-users/zsh-syntax-highlighting"

# Load asdf
source "/opt/asdf-vm/asdf.sh"

# Load and initialise completion system
autoload -Uz compinit
compinit
